# Generated by Django 2.1.5 on 2019-09-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=40, verbose_name='备注昵称')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMsgContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMsgToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='接收状态')),
                ('group_msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GroupMsgContent', verbose_name='群消息ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='群名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(verbose_name='入群时间')),
                ('group_nick', models.CharField(max_length=40, verbose_name='群内昵称')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Groups', verbose_name='群ID')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='接收状态')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('send_type', models.CharField(max_length=10, verbose_name='发送类型')),
            ],
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=65, verbose_name='密码')),
                ('nickname', models.CharField(max_length=40, verbose_name='昵称')),
                ('date_joined', models.DateTimeField(verbose_name='注册时间')),
                ('last_login', models.DateTimeField(default=None, verbose_name='上次登录时间')),
                ('last_ip', models.CharField(default=None, max_length=20, verbose_name='上次登录IP')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='database.UsersProfile', verbose_name='发送用户'),
        ),
        migrations.AddField(
            model_name='messages',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='database.UsersProfile', verbose_name='接收用户'),
        ),
        migrations.AddField(
            model_name='groupsusers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UsersProfile', verbose_name='群成员ID'),
        ),
        migrations.AddField(
            model_name='groups',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UsersProfile', verbose_name='群主ID'),
        ),
        migrations.AddField(
            model_name='groupmsgcontent',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UsersProfile', verbose_name='发送者ID'),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='database.UsersProfile', verbose_name='好友'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='database.UsersProfile', verbose_name='用户'),
        ),
    ]
