# Generated by Django 2.1.5 on 2019-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190917_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=20, verbose_name='用户名'), max_length=40, verbose_name='昵称'),
        ),
    ]
