# Generated by Django 2.1.5 on 2019-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190917_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='last_ip',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='上次登录IP'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='last_login',
            field=models.DateTimeField(default=None, null=True, verbose_name='上次登录时间'),
        ),
    ]
