# Generated by Django 2.1.5 on 2019-09-17 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190917_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='上次登录时间'),
        ),
    ]
